### ISSUE TITLE
Always include numbers in lists of RPG elements

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Editor-Qt#123]
The many drop down boxes in RPG Maker Editor for things like common events, animations, items, etc.. are super painful to navigate.

One thing that would really help is to include the number.

Like instead of `Long Sword` you'd have `0018: Long Sword` everywhere.

I would also include numbers in the treemap view for Maps. Its not easily matching up map id's to map names in RPG Maker Editor.

**Comment by carstene1ns** [comment]
What also annoys me is that you always need to navigate to another tab to change stuff.
I would like some `double click` or `right click` → `go to` context menu to change the currently selected item, weapon, event, etc.
Either this changes the current tab and scrolls to it (likely bad) or launches a popup with a similar window layout of the tab, but sans the drop down.

**Comment by Ghabry** [comment]
Also all the comboboxes should be editable and support searching.
So you can either type name or ID and it will list in a dropdown all items that match this filter criteria.

I wonder how hard it is to render some kind of "Go to" button next to the dropdown arrow to allow jumping to this element directly :)

> I would like some double click or right click → go to context menu to change the currently selected item, weapon, event, etc

That's exactly what I want to achieve in this branch: https://github.com/Ghabry/easyrpg-editor-qt/tree/actor-db

By decoupling the lists on the left (the one that lists all actors, skills, common events, etc.) of the Database from the right part of the UI you can spawn the widgets on the right as new windows :).
Though new windows is critical because two editor windows at once can easily desync and segfault. Maybe could be solved like the KDE Settings Panel does it: When two windows would show the same content the second window shows "This view is already open in a seperate window".

**Comment by Ghabry** [comment]
Our issue tracking is a bit sloppy here. 
The interface is not used everywhere yet but there are now ``RpgComboBox`` which show "Number: Name [...]".
So you get this feature "for free" everywhere just by using that class.
