### ISSUE TITLE
Question - End?

### ISSUE THREAD

**Issue by kholyphoenix1** [EasyRPG/Editor-Qt#81]
Hello, 

The development of this program is still active?
Thanks a lot!

**Comment by Ghabry** [comment]
Hey, the project is still active, it just progresses extremely slow and I don't think this will change soon :(

Basicly all our devs are working on the Player currently https://github.com/EasyRPG/Player .

Because we are compatible to RPG Maker 2000/2003 you can create your games with these commercial (!) programs and import them in our editor when it ever finishes.

Concerning other RPG Maker like projects I'm not aware of any active open source one that I could recommend.

**Comment by kholyphoenix1** [comment]
I understand. I was looking at the other as Open RPGMaker and RPGBoss . More it seems they are discontinued ...

**Comment by Ghabry** [comment]
It is active
